# Google account information
# create a file called gdata.yml in the config directory with your account info for maps interface
gdata_maps_production:
  feeds_url: "http://maps.google.com/maps/feeds"
  client_login_service: local
  authsub_scope: http://maps.google.com/maps/feeds
  username: USERNAME
  password: "PASSWORD"
  map: PRODUCTION_MAP

gdata_maps_development:
  feeds_url: "http://maps.google.com/maps/feeds"
  client_login_service: local
  authsub_scope: http://maps.google.com/maps/feeds
  username: USERNAME
  password: "PASSWORD"
  map: DEVELOPMENT_MAP

gdata_maps_test:
  feeds_url: "http://maps.google.com/maps/feeds"
  client_login_service: local
  authsub_scope: http://maps.google.com/maps/feeds
  username: USERNAME
  password: "PASSWORD"
  map: TEST_MAP
